/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Competitions */
        get: operations["list_competitions_competitions__get"];
        put?: never;
        /** Create Competition */
        post: operations["create_competition_competitions__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Competition */
        get: operations["retrieve_competition_competitions__name__get"];
        put?: never;
        post?: never;
        /** Delete Competition */
        delete: operations["delete_competition_competitions__name__delete"];
        options?: never;
        head?: never;
        /** Update Competition */
        patch: operations["update_competition_competitions__name__patch"];
        trace?: never;
    };
    "/competitions/{name}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Rating */
        get: operations["retrieve_rating_competitions__name__rating_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Rating */
        patch: operations["update_rating_competitions__name__rating_patch"];
        trace?: never;
    };
    "/competitions/{name}/player-ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Player Ratings */
        get: operations["retrieve_player_ratings_competitions__name__player_ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{name}/pairing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Pairing */
        get: operations["retrieve_pairing_competitions__name__pairing_get"];
        put?: never;
        /** Create Pairing */
        post: operations["create_pairing_competitions__name__pairing_post"];
        /** Delete Pairing */
        delete: operations["delete_pairing_competitions__name__pairing_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{name}/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Ranking */
        post: operations["create_ranking_competitions__name__ranking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/competitions/{name}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Round Registrations */
        get: operations["retrieve_round_registrations_competitions__name__registrations_get"];
        put?: never;
        post?: never;
        /** Delete Round Registrations */
        delete: operations["delete_round_registrations_competitions__name__registrations_delete"];
        options?: never;
        head?: never;
        /** Update Round Registrations */
        patch: operations["update_round_registrations_competitions__name__registrations_patch"];
        trace?: never;
    };
    "/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Players */
        get: operations["list_players_players__get"];
        put?: never;
        /** Create Player */
        post: operations["create_player_players__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Player */
        get: operations["retrieve_player_players__id___get"];
        put?: never;
        post?: never;
        /**
         * Delete Player
         * @description Delete a player, or deactivate them if they have competition history.
         *
         *     Ratings and external ids are owned by the player and cascade away with
         *     them, so they don't count as history.
         */
        delete: operations["delete_player_players__id___delete"];
        options?: never;
        head?: never;
        /** Update Player */
        patch: operations["update_player_players__id___patch"];
        trace?: never;
    };
    "/players/{id}/external-ids/{source}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Player External Id */
        put: operations["set_player_external_id_players__id__external_ids__source___put"];
        post?: never;
        /** Delete Player External Id */
        delete: operations["delete_player_external_id_players__id__external_ids__source___delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{id}/external-ratings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Player External Ratings */
        get: operations["list_player_external_ratings_players__id__external_ratings__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Matches */
        get: operations["list_matches_matches__get"];
        put?: never;
        /** Create Match */
        post: operations["create_match_matches__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/matches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve Match */
        get: operations["retrieve_match_matches__id__get"];
        put?: never;
        post?: never;
        /** Delete Match */
        delete: operations["delete_match_matches__id__delete"];
        options?: never;
        head?: never;
        /** Update Match */
        patch: operations["update_match_matches__id__patch"];
        trace?: never;
    };
    "/external/{source}/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search External Players */
        get: operations["search_external_players_external__source__search__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external/{source}/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import External Ratings
         * @description Import rating snapshots from an external source for a batch of players.
         *
         *     Which players: those in request.player_ids, or every player when it is
         *     None. Only players that have an external id for the source are looked up;
         *     the rest are reported back as players_without_id. Players that already
         *     have a snapshot at the list date are skipped (counted in skipped) unless
         *     request.update_existing is true. Batches of more than
         *     MAX_IMPORT_BATCH_SIZE looked-up players are rejected with a 400, since
         *     each player costs one request to the external API.
         *
         *     Which rating: the one at request.list_date ("YYYY-MM"), defaulting to the
         *     source's most recent list. If the source has no entry for a player at that
         *     exact date, the newest older entry is used instead; players unknown at the
         *     source (or with no entry at or before the date) are reported in not_found.
         *
         *     Each fetched rating is stored as an ExternalRating snapshot under the list
         *     date it actually came from — inserted if that (player, list date) snapshot
         *     is new (counted in imported), overwritten otherwise (counted in updated).
         *
         *     Returns an ExternalRatingImportResult summarizing all of the above.
         *     Responds 503 if the source has no configured provider and 502 if the
         *     external API fails.
         */
        post: operations["import_external_ratings_external__source__import__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /**
         * CompetitionCreate
         * @description Request body of POST /competitions/.
         */
        CompetitionCreate: {
            /** Name */
            name: string;
            type: components["schemas"]["CompetitionType"];
            rating_type: components["schemas"]["CompetitionRatingTypeCreate"];
        };
        /**
         * CompetitionDetail
         * @description A competition as returned by GET /competitions/{name} and the write endpoints.
         */
        CompetitionDetail: {
            /** Name */
            name: string;
            type: components["schemas"]["CompetitionType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** N Rounds */
            n_rounds: number;
            rating_type: components["schemas"]["CompetitionRatingTypePublic"];
        };
        /**
         * CompetitionPublic
         * @description A competition as returned by GET /competitions/.
         */
        CompetitionPublic: {
            /** Name */
            name: string;
            type: components["schemas"]["CompetitionType"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompetitionRatingForPlayer
         * @description A rating as nested in the PlayerDetail returned by GET /players/{id}/.
         *
         *     Seen from the player's side: it keeps the rating type (which names the
         *     competition) and drops the player. Its sibling is CompetitionRatingPublic.
         */
        CompetitionRatingForPlayer: {
            /** Id */
            id: number;
            /** Initial Rating */
            initial_rating: number;
            /** Current Rating */
            current_rating: number;
            /** Is Manual */
            is_manual: boolean;
            /** Source External Rating Id */
            source_external_rating_id: number | null;
            rating_type: components["schemas"]["CompetitionRatingTypePublic"];
        };
        /**
         * CompetitionRatingPublic
         * @description A rating as returned by GET /competitions/{name}/player-ratings.
         *
         *     Seen from the competition's side: it keeps the player and drops the rating
         *     type, which is the same for every row. Its sibling is
         *     CompetitionRatingForPlayer.
         */
        CompetitionRatingPublic: {
            /** Id */
            id: number;
            /** Player Id */
            player_id: number;
            player: components["schemas"]["PlayerRef"];
            /** Rating Type Id */
            rating_type_id: number;
            /** Initial Rating */
            initial_rating: number;
            /** Current Rating */
            current_rating: number;
            /** Is Manual */
            is_manual: boolean;
            /** Source External Rating Id */
            source_external_rating_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompetitionRatingTypeCreate
         * @description The rating configuration nested in the body of POST /competitions/.
         */
        CompetitionRatingTypeCreate: {
            /** Name */
            name?: string | null;
            algorithm: components["schemas"]["RatingAlgorithm"];
            /** Algorithm Config */
            algorithm_config?: Record<string, never> | null;
            /** Default Initial Rating */
            default_initial_rating?: number | null;
        };
        /**
         * CompetitionRatingTypePublic
         * @description The rating configuration nested in a CompetitionDetail or a rating response.
         */
        CompetitionRatingTypePublic: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            algorithm: components["schemas"]["RatingAlgorithm"];
            /** Algorithm Config */
            algorithm_config: Record<string, never> | null;
            /** Competition Name */
            competition_name: string;
            /** Default Initial Rating */
            default_initial_rating: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CompetitionRatingTypeUpdate
         * @description Request body of PATCH /competitions/{name}/rating.
         */
        CompetitionRatingTypeUpdate: {
            /** Name */
            name?: string | null;
            algorithm?: components["schemas"]["RatingAlgorithm"] | null;
            /** Algorithm Config */
            algorithm_config?: Record<string, never> | null;
            /** Default Initial Rating */
            default_initial_rating?: number | null;
        };
        /**
         * CompetitionType
         * @enum {string}
         */
        CompetitionType: "simkro";
        /**
         * CompetitionUpdate
         * @description Request body of PATCH /competitions/{name}.
         */
        CompetitionUpdate: {
            /** Name */
            name?: string | null;
            type?: components["schemas"]["CompetitionType"] | null;
        };
        /**
         * ExternalPlayerResult
         * @description A player as found at an external rating source.
         */
        ExternalPlayerResult: {
            source: components["schemas"]["ExternalRatingSource"];
            /** External Id */
            external_id: string;
            /** Name */
            name: string;
            /** Country */
            country?: string | null;
            /** Title */
            title?: string | null;
            /** Rating */
            rating?: number | null;
            /** List Date */
            list_date?: string | null;
        };
        /**
         * ExternalRatingImportRequest
         * @description Request body of POST /external/{source}/import/.
         */
        ExternalRatingImportRequest: {
            /**
             * Player Ids
             * @description Players to import ratings for. Defaults to all players with an external id for the source.
             */
            player_ids?: number[] | null;
            /** List Date */
            list_date?: string | null;
            /**
             * Update Existing
             * @description Also fetch ratings for players that already have a snapshot at the list date, overwriting it. Defaults to skipping those players.
             * @default false
             */
            update_existing: boolean;
        };
        /**
         * ExternalRatingImportResult
         * @description Response of POST /external/{source}/import/.
         */
        ExternalRatingImportResult: {
            /** List Date */
            list_date: string;
            /** Imported */
            imported: number;
            /** Updated */
            updated: number;
            /**
             * Skipped
             * @default 0
             */
            skipped: number;
            /**
             * Not Found
             * @default []
             */
            not_found: string[];
            /**
             * Players Without Id
             * @default []
             */
            players_without_id: number[];
        };
        /**
         * ExternalRatingPublic
         * @description A rating snapshot as returned by GET /players/{id}/external-ratings/.
         */
        ExternalRatingPublic: {
            /** Id */
            id: number;
            /** Player External Id Id */
            player_external_id_id: number;
            source: components["schemas"]["ExternalRatingSource"];
            /** Rating */
            rating: number;
            /** List Date */
            list_date: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
        };
        /**
         * ExternalRatingSource
         * @enum {string}
         */
        ExternalRatingSource: "fide" | "knsb";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MatchCreate
         * @description Request body of POST /matches/.
         */
        MatchCreate: {
            /** Player White Id */
            player_white_id: number;
            /** Player Black Id */
            player_black_id: number;
            /** Competition Name */
            competition_name: string;
            /** Round */
            round: number;
            /** Board */
            board: number;
            result?: components["schemas"]["Result"] | null;
        };
        /**
         * MatchPublic
         * @description A match as returned by GET /matches/ and the match write endpoints.
         */
        MatchPublic: {
            /** Player White Id */
            player_white_id: number;
            /** Player Black Id */
            player_black_id: number;
            /** Competition Name */
            competition_name: string;
            /** Round */
            round: number;
            /** Board */
            board: number;
            result?: components["schemas"]["Result"] | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            player_white: components["schemas"]["PlayerRef"];
            player_black: components["schemas"]["PlayerRef"];
        };
        /**
         * MatchUpdate
         * @description Request body of PATCH /matches/{id}/.
         */
        MatchUpdate: {
            /** Player White Id */
            player_white_id?: number | null;
            /** Player Black Id */
            player_black_id?: number | null;
            /** Competition Name */
            competition_name?: string | null;
            /** Round */
            round?: number | null;
            /** Board */
            board?: number | null;
            result?: components["schemas"]["Result"] | null;
        };
        /**
         * ModeratorPublic
         * @description A moderator as returned by GET /auth/me.
         */
        ModeratorPublic: {
            /** Id */
            id: number;
            /** Username */
            username: string;
        };
        /**
         * PairingCreate
         * @description Request body of POST /competitions/{name}/pairing.
         */
        PairingCreate: {
            /** Round Nr */
            round_nr: number;
            /** Player Ids */
            player_ids: number[];
        };
        /**
         * PlayerCreate
         * @description Request body of POST /players/.
         */
        PlayerCreate: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * External Ids
             * @default []
             */
            external_ids: components["schemas"]["PlayerExternalIdCreate"][];
        };
        /**
         * PlayerDetail
         * @description A player as returned by GET /players/{id}/.
         */
        PlayerDetail: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * External Ids
             * @default []
             */
            external_ids: components["schemas"]["PlayerExternalIdPublic"][];
            /**
             * Competition Ratings
             * @default []
             */
            competition_ratings: components["schemas"]["CompetitionRatingForPlayer"][];
        };
        /**
         * PlayerExternalIdCreate
         * @description An external id nested in the body of POST /players/.
         */
        PlayerExternalIdCreate: {
            source: components["schemas"]["ExternalRatingSource"];
            /** External Id */
            external_id: string;
        };
        /**
         * PlayerExternalIdPublic
         * @description A player's id at an external source, as returned inside a player response.
         *
         *     `rating` is the snapshot selected by the request's `list_date`: the newest
         *     snapshot at or before that date, or the newest one overall when no date is
         *     given. It is None when no snapshot has been imported yet.
         */
        PlayerExternalIdPublic: {
            /** Id */
            id: number;
            source: components["schemas"]["ExternalRatingSource"];
            /** External Id */
            external_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            rating?: components["schemas"]["ExternalRatingPublic"] | null;
        };
        /**
         * PlayerExternalIdUpdate
         * @description Request body of PUT /players/{id}/external-ids/{source}/.
         */
        PlayerExternalIdUpdate: {
            /** External Id */
            external_id: string;
        };
        /**
         * PlayerPublic
         * @description A player as returned by GET /players/ and the player write endpoints.
         */
        PlayerPublic: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * External Ids
             * @default []
             */
            external_ids: components["schemas"]["PlayerExternalIdPublic"][];
        };
        /**
         * PlayerRef
         * @description A player as nested in a match, a registration or a competition rating.
         */
        PlayerRef: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /**
         * PlayerUpdate
         * @description Request body of PATCH /players/{id}/.
         */
        PlayerUpdate: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * RatingAlgorithm
         * @enum {string}
         */
        RatingAlgorithm: "elo";
        /**
         * Result
         * @enum {string}
         */
        Result: "1-0" | "1/2-1/2" | "0-1";
        /**
         * RoundRegistrationPublic
         * @description A round registration as returned by GET /competitions/{name}/registrations.
         */
        RoundRegistrationPublic: {
            /** Id */
            id: number;
            player: components["schemas"]["PlayerRef"];
            /** Is Bye */
            is_bye: boolean;
            /** Initial Rating */
            initial_rating: number | null;
        };
        /**
         * RoundRegistrationUpdate
         * @description Request body of PATCH /competitions/{name}/registrations.
         */
        RoundRegistrationUpdate: {
            /** Player Ids To Add */
            player_ids_to_add?: number[] | null;
            /** Player Ids To Remove */
            player_ids_to_remove?: number[] | null;
            /** Bye Player Id */
            bye_player_id?: number | null;
            /** Clear Bye */
            clear_bye?: boolean | null;
            /** Initial Ratings */
            initial_ratings?: {
                [key: string]: number;
            } | null;
        };
        /**
         * SimkroRank
         * @description A ranking row as returned by GET|POST /competitions/{name}/ranking.
         */
        SimkroRank: {
            /** Position */
            position: number;
            player: components["schemas"]["PlayerRef"];
            /** Games Played */
            games_played: number;
            /** Saldo */
            saldo: number;
            /** Points */
            points: number;
            /** Color Saldo */
            color_saldo: number;
            /** Wins */
            wins: number;
            /** Draws */
            draws: number;
            /** Losses */
            losses: number;
            /** Current Rating */
            current_rating?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModeratorPublic"];
                };
            };
        };
    };
    list_competitions_competitions__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_competition_competitions__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_competition_competitions__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_competition_competitions__name__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_competition_competitions__name__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_rating_competitions__name__rating_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRatingTypePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rating_competitions__name__rating_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompetitionRatingTypeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRatingTypePublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_player_ratings_competitions__name__player_ratings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompetitionRatingPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_pairing_competitions__name__pairing_get: {
        parameters: {
            query?: {
                round_nr?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_pairing_competitions__name__pairing_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_pairing_competitions__name__pairing_delete: {
        parameters: {
            query: {
                round_nr: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_ranking_competitions__name__ranking_post: {
        parameters: {
            query?: {
                round_nr?: number | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimkroRank"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_round_registrations_competitions__name__registrations_get: {
        parameters: {
            query: {
                round_nr: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRegistrationPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_round_registrations_competitions__name__registrations_delete: {
        parameters: {
            query: {
                round_nr: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_round_registrations_competitions__name__registrations_patch: {
        parameters: {
            query: {
                round_nr: number;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundRegistrationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoundRegistrationPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_players_players__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                is_active?: boolean | null;
                /** @description Rating list to report external ratings for, as YYYY-MM. Defaults to the newest snapshot of each player. */
                list_date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_player_players__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_player_players__id___get: {
        parameters: {
            query?: {
                /** @description Rating list to report external ratings for, as YYYY-MM. Defaults to the newest snapshot of each player. */
                list_date?: string | null;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_players__id___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__id___patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_player_external_id_players__id__external_ids__source___put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                source: components["schemas"]["ExternalRatingSource"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerExternalIdUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerExternalIdPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_player_external_id_players__id__external_ids__source___delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                source: components["schemas"]["ExternalRatingSource"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_player_external_ratings_players__id__external_ratings__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalRatingPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_matches_matches__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_match_matches__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retrieve_match_matches__id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_match_matches__id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_match_matches__id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_external_players_external__source__search__get: {
        parameters: {
            query: {
                query: string;
                limit?: number;
            };
            header?: never;
            path: {
                source: components["schemas"]["ExternalRatingSource"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalPlayerResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_external_ratings_external__source__import__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source: components["schemas"]["ExternalRatingSource"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalRatingImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalRatingImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
