"""baseline schema

Revision ID: 1e123c1112b5
Revises:
Create Date: 2026-08-25 20:39:55.088982

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "1e123c1112b5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # This is the baseline: the schema as `SQLModel.metadata.create_all` left it
    # on the day Alembic was introduced. A database from before then already has
    # every table, so replaying the creates would fail -- treat it as applied
    # instead. That keeps the production file, the developer files and the
    # downloaded backups all upgradable without a manual `alembic stamp`.
    if sa.inspect(op.get_bind()).has_table("player"):
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sa.Enum("SIMKRO", name="competitiontype"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("competition", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_competition_name"), ["name"], unique=True)

    op.create_table(
        "moderator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("moderator", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_moderator_username"), ["username"], unique=True
        )

    op.create_table(
        "player",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "competitionratingtype",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("algorithm", sa.Enum("ELO", name="ratingalgorithm"), nullable=False),
        sa.Column("algorithm_config", sa.JSON(), nullable=True),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("default_initial_rating", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competition.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competition_id"),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_white_id", sa.Integer(), nullable=False),
        sa.Column("player_black_id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("board", sa.Integer(), nullable=False),
        sa.Column(
            "result",
            sa.Enum("WHITE_WIN", "DRAW", "BLACK_WIN", name="result"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competition.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_black_id"],
            ["player.id"],
        ),
        sa.ForeignKeyConstraint(
            ["player_white_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("round", "board", "competition_id"),
    )
    op.create_table(
        "playerexternalid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("FIDE", "KNSB", name="externalratingsource"),
            nullable=False,
        ),
        sa.Column("external_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "source"),
        sa.UniqueConstraint("source", "external_id"),
    )
    op.create_table(
        "roundregistration",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("is_bye", sa.Boolean(), nullable=False),
        sa.Column("initial_rating", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_id"], ["competition.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["player.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competition_id", "round", "player_id"),
    )
    op.create_table(
        "externalrating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_external_id_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("list_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_external_id_id"], ["playerexternalid.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_external_id_id", "list_date"),
    )
    op.create_table(
        "competitionrating",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("rating_type_id", sa.Integer(), nullable=False),
        sa.Column("initial_rating", sa.Float(), nullable=False),
        sa.Column("current_rating", sa.Float(), nullable=False),
        sa.Column("is_manual", sa.Boolean(), nullable=False),
        sa.Column("source_external_rating_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["rating_type_id"], ["competitionratingtype.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_external_rating_id"], ["externalrating.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "rating_type_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("competitionrating")
    op.drop_table("externalrating")
    op.drop_table("roundregistration")
    op.drop_table("playerexternalid")
    op.drop_table("match")
    op.drop_table("competitionratingtype")
    op.drop_table("player")
    with op.batch_alter_table("moderator", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_moderator_username"))

    op.drop_table("moderator")
    with op.batch_alter_table("competition", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_competition_name"))

    op.drop_table("competition")
    # ### end Alembic commands ###
